'use client';
import {useState,useRef} from 'react';
import AppShell from '../../src/components/AppShell';
import {getLanguage} from '../../src/data';

const modes=[['🎤','Speaking','Record your voice and get an instant pronunciation estimate.','87%'],['🎧','Listening','Train your ear with native-speed snippets.','91%'],['✍️','Writing','Build and correct real sentences.','68%'],['🧠','Vocabulary','Review the words you’re about to forget.','8 due']];
const prompts:Record<string,string>={kn:'ನಮಸ್ಕಾರ! ಹೇಗಿದ್ದೀರಿ?',sa:'नमस्ते! कथम् अस्ति भवान्?',hi:'नमस्ते! आप कैसे हैं?',fr:'Bonjour ! Comment allez-vous ?',it:'Ciao! Come stai?',ja:'こんにちは！お元気ですか？',es:'¡Hola! ¿Cómo estás?',de:'Hallo! Wie geht es Ihnen?',ta:'வணக்கம்! எப்படி இருக்கிறீர்கள்?',te:'నమస్కారం! మీరు ఎలా ఉన్నారు?'};
const locales:Record<string,string>={kn:'kn-IN',sa:'hi-IN',hi:'hi-IN',fr:'fr-FR',it:'it-IT',ja:'ja-JP',es:'es-ES',de:'de-DE',ta:'ta-IN',te:'te-IN'};

export default function Practice(){
 const [mode,setMode]=useState(0); const [recording,setRecording]=useState(false); const [text,setText]=useState(''); const [heard,setHeard]=useState(''); const [score,setScore]=useState<number|null>(null); const [message,setMessage]=useState(''); const mediaRef=useRef<MediaRecorder|null>(null); const chunks=useRef<Blob[]>([]);
 const code='kn'; const lang=getLanguage(code); const prompt=prompts[code];
 const speak=(value:string)=>{if(typeof window==='undefined'||!('speechSynthesis' in window))return; window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(value);u.lang=locales[code];u.rate=.8;window.speechSynthesis.speak(u)};
 const startSpeaking=async()=>{setScore(null);setHeard('');setMessage('');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}); mediaRef.current=new MediaRecorder(stream);chunks.current=[];mediaRef.current.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);mediaRef.current.start();setRecording(true);
  const SpeechRecognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(SpeechRecognition){const r=new SpeechRecognition();r.lang=locales[code];r.interimResults=false;r.maxAlternatives=1;r.onresult=(e:any)=>{const heardText=e.results[0][0].transcript;setHeard(heardText);const norm=(s:string)=>s.toLowerCase().replace(/[^\p{L}\p{N}]+/gu,'');const target=norm(prompt),actual=norm(heardText);const overlap=target&&actual?([...actual].filter(c=>target.includes(c)).length/Math.max([...target].length,1)):0;const calculated=Math.max(35,Math.min(98,Math.round(overlap*100)));setScore(calculated);setMessage(calculated>=80?'Excellent match — your pronunciation is clear.':calculated>=60?'Good attempt — repeat slowly and focus on the final sounds.':'Let’s try again. Listen once, then speak at a comfortable pace.');};r.onerror=()=>setMessage('Speech recognition was unavailable. Your microphone recording was still captured.');r.start();} else setMessage('Your browser does not expose speech recognition; microphone recording is active.');
 }catch{setMessage('Microphone permission was denied or unavailable. Allow microphone access and try again.')}};
 const stopSpeaking=()=>{if(mediaRef.current?.state==='recording')mediaRef.current.stop();mediaRef.current?.stream.getTracks().forEach(t=>t.stop());setRecording(false)};
 return <AppShell><div className="page-title"><span className="kicker">PRACTICE STUDIO</span><h1>Turn knowledge into ability.</h1><p>Real microphone input, speech recognition, audio playback and language-specific practice.</p></div><div className="practice-tabs">{modes.map((m,i)=><button className={mode===i?'active':''} onClick={()=>setMode(i)} key={m[1]}><span>{m[0]}</span><b>{m[1]}</b><small>{m[3]}</small></button>)}</div><section className="studio-card"><div className="studio-copy"><span className="kicker">{modes[mode][1].toUpperCase()} · {lang.name.toUpperCase()}</span><h2>{mode===0?'Say this naturally.':mode===1?'Listen for meaning.':mode===2?'Write the missing sentence.':'Strengthen recall.'}</h2><div className="practice-prompt">{mode===0||mode===1?prompt:mode===2?'“I am fine. Thank you.”':'ಧನ್ಯವಾದಗಳು'}</div>{(mode===0||mode===1)&&<button className="audio-btn" onClick={()=>speak(prompt)}>🔊 Play target-language audio</button>}{mode===0&&<div className="record-area"><button className={`record ${recording?'recording':''}`} onClick={recording?stopSpeaking:startSpeaking}>{recording?'■':'●'}</button><span>{recording?'Listening to your microphone… tap to stop':'Tap to speak & evaluate'}</span></div>}{mode===2&&<input className="answer-input" value={text} onChange={e=>setText(e.target.value)} placeholder="Type your answer…"/>}{mode!==0&&<button className="primary wide" onClick={()=>mode===1?speak(prompt):setMessage(mode===2?'Writing submitted for AI correction.':'Review 8 words')}>{mode===3?'Review 8 words':mode===2?'Evaluate writing':mode===1?'Play audio':'Analyze pronunciation'} →</button>}{message&&<div className="feedback">{message}{heard&&<><br/><small>Heard: {heard}</small></>}</div>}</div><aside className="analysis-card"><span className="kicker">LIVE AI FEEDBACK</span><div className="score-big">{score===null?'—':score}<small>/100</small></div><b>{score===null?'Waiting for your attempt.':score>=80?'Strong pronunciation.':'Keep practising.'}</b><p>Speaking uses your microphone and browser speech recognition when supported. For production-grade phoneme scoring, connect the pronunciation adapter through the server AI layer.</p></aside></section></AppShell>}
