'use client';
import {useEffect,useState,useRef} from 'react';
import AppShell from '../../src/components/AppShell';
import {languageCatalog} from '../../src/learning/languageCatalog';
import {getSpeechProfile} from '../../src/learning/speech';

const modes=[['🎤','Speaking','Record your voice and get pronunciation feedback.',''],['🎧','Listening','Train your ear with native-speed snippets.',''],['✍️','Writing','Build and correct real sentences.',''],['🧠','Vocabulary','Review the words you’re about to forget.','']];
const prompts:Record<string,string>={kn:'ನಮಸ್ಕಾರ! ಹೇಗಿದ್ದೀರಿ?',sa:'नमस्ते! कथम् अस्ति भवान्?',hi:'नमस्ते! आप कैसे हैं?',fr:'Bonjour ! Comment allez-vous ?',it:'Ciao! Come stai?',ja:'こんにちは！お元気ですか？',es:'¡Hola! ¿Cómo estás?',de:'Hallo! Wie geht es Ihnen?',ta:'வணக்கம்! எப்படி இருக்கிறீர்கள்?',te:'నమస్కారం! మీరు ఎలా ఉన్నారు?'};

export default function Practice(){
 const [mode,setMode]=useState(0); const [code,setCode]=useState('kn'); const [recording,setRecording]=useState(false); const [text,setText]=useState(''); const [heard,setHeard]=useState(''); const [score,setScore]=useState<number|null>(null); const [message,setMessage]=useState(''); const [wordFeedback,setWordFeedback]=useState<any[]>([]); const [prompt,setPrompt]=useState(prompts.kn); const mediaRef=useRef<MediaRecorder|null>(null); const chunks=useRef<Blob[]>([]);
 const lang=languageCatalog.find(l=>l.code===code)||languageCatalog[0]; const profile=getSpeechProfile(code);
 useEffect(()=>{let cancelled=false;setPrompt(prompts[code]||'');if(prompts[code])return()=>{cancelled=true};(async()=>{try{const r=await fetch('/api/ai/lesson',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({language:lang.name,native:lang.native,code,level:1,topic:'a natural greeting and introduction'})});const data=await r.json();if(!cancelled&&data.dialogue?.[0]?.[1])setPrompt(data.dialogue[0][1]);}catch{}return()=>{cancelled=true}})();return()=>{cancelled=true}},[code,lang.name,lang.native]);
 const playAudio=async(value:string)=>{setMessage('Generating target-language audio…');try{const r=await fetch('/api/ai/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:value,languageCode:code,pace:.9})});const type=r.headers.get('content-type')||'';if(type.includes('audio/')){const audio=new Audio(URL.createObjectURL(await r.blob()));await audio.play();setMessage('');return;}const data=await r.json();if(data.provider==='browser'&&'speechSynthesis' in window){const u=new SpeechSynthesisUtterance(value);u.lang=profile.locale;u.rate=.9;window.speechSynthesis.cancel();window.speechSynthesis.speak(u);setMessage('Using the browser voice available for this language.')}else setMessage(data.reason||'No speech provider configured.');}catch(e){setMessage(e instanceof Error?e.message:'Audio failed.');}};
 const startSpeaking=async()=>{setScore(null);setHeard('');setMessage('');setWordFeedback([]);try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const recorder=new MediaRecorder(stream);mediaRef.current=recorder;chunks.current=[];recorder.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks.current,{type:'audio/webm'});const form=new FormData();form.append('file',blob,'speaking.webm');form.append('languageCode',code);form.append('target',prompt);try{const r=await fetch('/api/ai/transcribe',{method:'POST',body:form});const data=await r.json();if(!r.ok)throw new Error(data.error||'Speech recognition failed');setHeard(data.transcript||'');setScore(data.scoring?.score??null);setWordFeedback(data.scoring?.feedback||[]);setMessage(data.provider==='browser'?'No server speech provider is configured.':'Speech recognized. Review each word below and retry.');}catch(e){setMessage(e instanceof Error?e.message:'Speech recognition failed.');}};recorder.start();setRecording(true);}catch{setMessage('Microphone permission was denied or unavailable. Allow microphone access and try again.')}};
 const stopSpeaking=()=>{if(mediaRef.current?.state==='recording')mediaRef.current.stop();setRecording(false)};
 return <AppShell><div className="page-title"><span className="kicker">PRACTICE STUDIO</span><h1>Turn knowledge into ability.</h1><p>Choose a language, hear the target sentence, record yourself, and receive word-level feedback.</p></div><div className="practice-language-picker"><span>Practice language</span><select value={code} onChange={e=>{setCode(e.target.value);setScore(null);setHeard('');setMessage('')}}>{languageCatalog.map(l=><option value={l.code} key={l.code}>{l.name} · {l.native}</option>)}</select></div><div className="practice-tabs">{modes.map((m,i)=><button className={mode===i?'active':''} onClick={()=>setMode(i)} key={m[1]}><span>{m[0]}</span><b>{m[1]}</b><small>{m[3]||'Adaptive'}</small></button>)}</div><section className="studio-card"><div className="studio-copy"><span className="kicker">{modes[mode][1].toUpperCase()} · {lang.name.toUpperCase()}</span><h2>{mode===0?'Say this naturally.':mode===1?'Listen for meaning.':mode===2?'Write the missing sentence.':'Strengthen recall.'}</h2><div className="practice-prompt">{mode===0||mode===1?prompt:mode===2?'“I am fine. Thank you.”':lang.native}</div>{(mode===0||mode===1)&&<button className="audio-btn" onClick={()=>playAudio(prompt)}>🔊 Play {lang.name} audio</button>}{mode===0&&<div className="record-area"><button className={`record ${recording?'recording':''}`} onClick={recording?stopSpeaking:startSpeaking}>{recording?'■':'●'}</button><span>{recording?'Listening to your microphone… tap to stop':'Tap to speak & evaluate'}</span></div>}{mode===2&&<input className="answer-input" value={text} onChange={e=>setText(e.target.value)} placeholder="Type your answer…"/>}{mode!==0&&<button className="primary wide" onClick={()=>mode===1?playAudio(prompt):setMessage(mode===2?'Writing submitted for AI correction.':'Review vocabulary')}>{mode===3?'Review vocabulary':mode===2?'Evaluate writing':'Play audio'} →</button>}{message&&<div className="feedback">{message}{heard&&<><br/><small>Heard: {heard}</small></>}</div>}{wordFeedback.length>0&&<div className="word-feedback">{wordFeedback.map(x=><span className={x.status} key={`${x.word}-${x.spoken}`}>{x.word}{x.status==='correct'?' ✓':x.status==='missing'?' ✕':' → '+x.spoken}</span>)}</div>}</div><aside className="analysis-card"><span className="kicker">PRONUNCIATION COACH</span><div className="score-big">{score===null?'—':score}<small>/100</small></div><b>{score===null?'Waiting for your attempt.':score>=90?'Excellent clarity.':score>=75?'Strong attempt.':score>=55?'Good start — retry the highlighted words.':'Let’s slow down and retry.'}</b><p>{profile.pronunciationNotes.join(' ')||'Speak clearly and focus on the target language sounds.'}</p></aside></section></AppShell>}
