export type CatalogLanguage={code:string;name:string;native:string;region:string;script:string;locale:string;difficulty:string};

export const languageCatalog:CatalogLanguage[]=[
{code:'as',name:'Assamese',native:'অসমীয়া',region:'India',script:'Assamese',locale:'as-IN',difficulty:'Moderate'},
{code:'bn',name:'Bengali',native:'বাংলা',region:'India',script:'Bengali',locale:'bn-IN',difficulty:'Moderate'},
{code:'brx',name:'Bodo',native:'बड़ो',region:'India',script:'Devanagari',locale:'brx-IN',difficulty:'Advanced'},
{code:'doi',name:'Dogri',native:'डोगरी',region:'India',script:'Devanagari',locale:'doi-IN',difficulty:'Advanced'},
{code:'gu',name:'Gujarati',native:'ગુજરાતી',region:'India',script:'Gujarati',locale:'gu-IN',difficulty:'Moderate'},
{code:'hi',name:'Hindi',native:'हिन्दी',region:'India',script:'Devanagari',locale:'hi-IN',difficulty:'Easy'},
{code:'kn',name:'Kannada',native:'ಕನ್ನಡ',region:'India',script:'Kannada',locale:'kn-IN',difficulty:'Moderate'},
{code:'kok',name:'Konkani',native:'कोंकणी',region:'India',script:'Devanagari',locale:'kok-IN',difficulty:'Advanced'},
{code:'ks',name:'Kashmiri',native:'कॉशुर',region:'India',script:'Perso-Arabic/Devanagari',locale:'ks-IN',difficulty:'Advanced'},
{code:'mai',name:'Maithili',native:'मैथिली',region:'India',script:'Devanagari',locale:'mai-IN',difficulty:'Advanced'},
{code:'ml',name:'Malayalam',native:'മലയാളം',region:'India',script:'Malayalam',locale:'ml-IN',difficulty:'Advanced'},
{code:'mr',name:'Marathi',native:'मराठी',region:'India',script:'Devanagari',locale:'mr-IN',difficulty:'Moderate'},
{code:'mni',name:'Manipuri',native:'মৈতৈলোন্',region:'India',script:'Meitei/Bengali',locale:'mni-IN',difficulty:'Advanced'},
{code:'ne',name:'Nepali',native:'नेपाली',region:'India',script:'Devanagari',locale:'ne-IN',difficulty:'Moderate'},
{code:'or',name:'Odia',native:'ଓଡ଼ିଆ',region:'India',script:'Odia',locale:'od-IN',difficulty:'Moderate'},
{code:'pa',name:'Punjabi',native:'ਪੰਜਾਬੀ',region:'India',script:'Gurmukhi',locale:'pa-IN',difficulty:'Moderate'},
{code:'sa',name:'Sanskrit',native:'संस्कृतम्',region:'India',script:'Devanagari',locale:'sa-IN',difficulty:'Advanced'},
{code:'sat',name:'Santali',native:'ᱥᱟᱱᱛᱟᱲᱤ',region:'India',script:'Ol Chiki',locale:'sat-IN',difficulty:'Advanced'},
{code:'sd',name:'Sindhi',native:'سنڌي',region:'India',script:'Perso-Arabic/Devanagari',locale:'sd-IN',difficulty:'Advanced'},
{code:'ta',name:'Tamil',native:'தமிழ்',region:'India',script:'Tamil',locale:'ta-IN',difficulty:'Moderate'},
{code:'te',name:'Telugu',native:'తెలుగు',region:'India',script:'Telugu',locale:'te-IN',difficulty:'Moderate'},
{code:'ur',name:'Urdu',native:'اردو',region:'India',script:'Perso-Arabic',locale:'ur-IN',difficulty:'Advanced'},
{code:'en',name:'English',native:'English',region:'Global',script:'Latin',locale:'en-US',difficulty:'Easy'},
{code:'fr',name:'French',native:'Français',region:'Europe',script:'Latin',locale:'fr-FR',difficulty:'Moderate'},
{code:'de',name:'German',native:'Deutsch',region:'Europe',script:'Latin',locale:'de-DE',difficulty:'Moderate'},
{code:'es',name:'Spanish',native:'Español',region:'Europe',script:'Latin',locale:'es-ES',difficulty:'Easy'},
{code:'it',name:'Italian',native:'Italiano',region:'Europe',script:'Latin',locale:'it-IT',difficulty:'Easy'},
{code:'pt',name:'Portuguese',native:'Português',region:'Europe',script:'Latin',locale:'pt-PT',difficulty:'Moderate'},
{code:'ja',name:'Japanese',native:'日本語',region:'Asia',script:'Japanese',locale:'ja-JP',difficulty:'Advanced'},
{code:'ko',name:'Korean',native:'한국어',region:'Asia',script:'Hangul',locale:'ko-KR',difficulty:'Advanced'},
{code:'zh',name:'Mandarin Chinese',native:'中文',region:'Asia',script:'Han',locale:'zh-CN',difficulty:'Advanced'},
{code:'ar',name:'Arabic',native:'العربية',region:'Middle East',script:'Arabic',locale:'ar-SA',difficulty:'Advanced'},
{code:'ru',name:'Russian',native:'Русский',region:'Europe',script:'Cyrillic',locale:'ru-RU',difficulty:'Advanced'},
];

export function getCatalogLanguage(code:string){return languageCatalog.find(l=>l.code===code)||languageCatalog[0];}
