export type Language = { code:string; name:string; native:string; region:string; framework:string; script:string; level:string; learners:string; difficulty:string; glyph:string; tone:string; progress:number };
export type Lesson = { id:string; language:string; code:string; title:string; subtitle:string; duration:string; xp:number; vocabulary:string[][]; dialogue:string[][]; exercises:{type:string;prompt:string;answer:string;options:string[]}[] };

export const languages: Language[] = [
{code:'kn',name:'Kannada',native:'ಕನ್ನಡ',region:'India',framework:'Internal levels',script:'Kannada',level:'Beginner',learners:'1.2M',difficulty:'Moderate',glyph:'ಕ',tone:'sage',progress:28},
{code:'sa',name:'Sanskrit',native:'संस्कृतम्',region:'India',framework:'Internal levels',script:'Devanagari',level:'Beginner',learners:'420K',difficulty:'Advanced',glyph:'सं',tone:'amber',progress:12},
{code:'hi',name:'Hindi',native:'हिन्दी',region:'India',framework:'CEFR-aligned',script:'Devanagari',level:'Beginner',learners:'4.8M',difficulty:'Easy',glyph:'ह',tone:'rose',progress:64},
{code:'fr',name:'French',native:'Français',region:'Europe',framework:'CEFR',script:'Latin',level:'A1',learners:'3.1M',difficulty:'Moderate',glyph:'Fr',tone:'blue',progress:0},
{code:'it',name:'Italian',native:'Italiano',region:'Europe',framework:'CEFR',script:'Latin',level:'A1',learners:'1.7M',difficulty:'Easy',glyph:'It',tone:'violet',progress:0},
{code:'ja',name:'Japanese',native:'日本語',region:'Asia',framework:'Internal levels',script:'Japanese',level:'A1',learners:'2.4M',difficulty:'Advanced',glyph:'日',tone:'sun',progress:0},
{code:'es',name:'Spanish',native:'Español',region:'Europe',framework:'CEFR',script:'Latin',level:'A1',learners:'5.2M',difficulty:'Easy',glyph:'Es',tone:'rose',progress:0},
{code:'de',name:'German',native:'Deutsch',region:'Europe',framework:'CEFR',script:'Latin',level:'A1',learners:'1.8M',difficulty:'Moderate',glyph:'De',tone:'amber',progress:0},
{code:'ta',name:'Tamil',native:'தமிழ்',region:'India',framework:'Internal levels',script:'Tamil',level:'Beginner',learners:'860K',difficulty:'Moderate',glyph:'த',tone:'violet',progress:0},
{code:'te',name:'Telugu',native:'తెలుగు',region:'India',framework:'Internal levels',script:'Telugu',level:'Beginner',learners:'740K',difficulty:'Moderate',glyph:'త',tone:'sage',progress:0},
];

const seedLessons: Record<string, Lesson> = {
kn:{id:'kn-greetings-01',language:'Kannada',code:'kn',title:'Your First Kannada Conversation',subtitle:'Meet, greet, and make your first four sentences.',duration:'12 min',xp:50,vocabulary:[['ನಮಸ್ಕಾರ','Namaskāra','Hello'],['ಹೇಗಿದ್ದೀರಿ?','Hēgiddīri?','How are you?'],['ಚೆನ್ನಾಗಿದ್ದೇನೆ','Chennāgiddēne','I am fine'],['ಧನ್ಯವಾದಗಳು','Dhanyāvadagalu','Thank you']],dialogue:[['Anu','ನಮಸ್ಕಾರ!','Hello!'],['Ravi','ನಮಸ್ಕಾರ! ಹೇಗಿದ್ದೀರಿ?','Hello! How are you?'],['Anu','ಚೆನ್ನಾಗಿದ್ದೇನೆ. ಧನ್ಯವಾದಗಳು.','I am fine. Thank you.']],exercises:[{type:'listen',prompt:'Listen and choose the meaning',answer:'I am fine',options:['Good morning','I am fine','Thank you','Goodbye']},{type:'match',prompt:'What does ಧನ್ಯවාದಗಳು mean?',answer:'Thank you',options:['Hello','How are you?','Thank you','I am fine']},{type:'order',prompt:'Build: “I am fine.”',answer:'ಚೆನ್ನಾಗಿದ್ದೇನೆ',options:['ನಮಸ್ಕಾರ','ಚೆನ್ನಾಗಿದ್ದೇನೆ','ಧನ್ಯವಾದಗಳು','ಇಲ್ಲ']}]},
sa:{id:'sa-greetings-01',language:'Sanskrit',code:'sa',title:'Your First Sanskrit Conversation',subtitle:'Greet someone and introduce a simple everyday exchange.',duration:'12 min',xp:50,vocabulary:[['नमस्ते','Namaste','Hello'],['कथम् अस्ति भवान्?','Katham asti bhavān?','How are you?'],['अहं कुशली अस्मि','Ahaṃ kuśalī asmi','I am well'],['धन्यवादः','Dhanyavādaḥ','Thank you']],dialogue:[['Anu','नमस्ते!','Hello!'],['Ravi','नमस्ते! कथम् अस्ति भवान्?','Hello! How are you?'],['Anu','अहं कुशली अस्मि। धन्यवादः।','I am well. Thank you.']],exercises:[{type:'listen',prompt:'What does नमस्ते mean?',answer:'Hello',options:['Goodbye','Hello','Thank you','Sorry']},{type:'match',prompt:'What does धन्यवादः mean?',answer:'Thank you',options:['Hello','How are you?','Thank you','I am well']},{type:'order',prompt:'Choose the phrase for “I am well.”',answer:'अहं कुशली अस्मि',options:['नमस्ते','धन्यवादः','अहं कुशली अस्मि','कथम् अस्ति']}]},
hi:{id:'hi-greetings-01',language:'Hindi',code:'hi',title:'Your First Hindi Conversation',subtitle:'Say hello, ask how someone is, and respond naturally.',duration:'12 min',xp:50,vocabulary:[['नमस्ते','Namaste','Hello'],['आप कैसे हैं?','Aap kaise hain?','How are you?'],['मैं ठीक हूँ','Main ṭhīk hū̃','I am fine'],['धन्यवाद','Dhanyavaad','Thank you']],dialogue:[['Anu','नमस्ते!','Hello!'],['Ravi','नमस्ते! आप कैसे हैं?','Hello! How are you?'],['Anu','मैं ठीक हूँ। धन्यवाद।','I am fine. Thank you.']],exercises:[{type:'listen',prompt:'What does आप कैसे हैं? mean?',answer:'How are you?',options:['Hello','How are you?','Thank you','I am fine']},{type:'match',prompt:'What does धन्यवाद mean?',answer:'Thank you',options:['Hello','How are you?','Thank you','Goodbye']},{type:'order',prompt:'Choose “I am fine.”',answer:'मैं ठीक हूँ',options:['नमस्ते','मैं ठीक हूँ','धन्यवाद','आप कैसे हैं?']}]},
fr:{id:'fr-greetings-01',language:'French',code:'fr',title:'Your First French Conversation',subtitle:'Meet someone, ask how they are, and answer politely.',duration:'12 min',xp:50,vocabulary:[['Bonjour','Bonjour','Hello'],['Comment allez-vous ?','Comment allez-vous ?','How are you?'],['Je vais bien','Je vais bien','I am fine'],['Merci','Merci','Thank you']],dialogue:[['Anu','Bonjour !','Hello!'],['Ravi','Bonjour ! Comment allez-vous ?','Hello! How are you?'],['Anu','Je vais bien. Merci.','I am fine. Thank you.']],exercises:[{type:'listen',prompt:'What does Merci mean?',answer:'Thank you',options:['Hello','How are you?','Thank you','Goodbye']},{type:'match',prompt:'What does Bonjour mean?',answer:'Hello',options:['Hello','Thank you','I am fine','Goodbye']},{type:'order',prompt:'Choose “I am fine.”',answer:'Je vais bien',options:['Bonjour','Merci','Je vais bien','Comment allez-vous ?']}]},
it:{id:'it-greetings-01',language:'Italian',code:'it',title:'Your First Italian Conversation',subtitle:'Greet someone and make a friendly first exchange.',duration:'12 min',xp:50,vocabulary:[['Ciao','Ciao','Hello'],['Come stai?','Come stai?','How are you?'],['Sto bene','Sto bene','I am fine'],['Grazie','Grazie','Thank you']],dialogue:[['Anu','Ciao!','Hello!'],['Ravi','Ciao! Come stai?','Hello! How are you?'],['Anu','Sto bene. Grazie.','I am fine. Thank you.']],exercises:[{type:'listen',prompt:'What does Grazie mean?',answer:'Thank you',options:['Hello','Thank you','Goodbye','How are you?']},{type:'match',prompt:'What does Ciao mean?',answer:'Hello',options:['Hello','Thank you','I am fine','Sorry']},{type:'order',prompt:'Choose “I am fine.”',answer:'Sto bene',options:['Ciao','Grazie','Sto bene','Come stai?']}]},
ja:{id:'ja-greetings-01',language:'Japanese',code:'ja',title:'Your First Japanese Conversation',subtitle:'Use a polite greeting and a simple check-in.',duration:'12 min',xp:50,vocabulary:[['こんにちは','Konnichiwa','Hello'],['お元気ですか？','O-genki desu ka?','How are you?'],['元気です','Genki desu','I am well'],['ありがとう','Arigatō','Thank you']],dialogue:[['Anu','こんにちは！','Hello!'],['Ravi','こんにちは！お元気ですか？','Hello! How are you?'],['Anu','元気です。ありがとう。','I am well. Thank you.']],exercises:[{type:'listen',prompt:'What does ありがとう mean?',answer:'Thank you',options:['Hello','Thank you','Goodbye','How are you?']},{type:'match',prompt:'What does こんにちは mean?',answer:'Hello',options:['Hello','Thank you','I am well','Sorry']},{type:'order',prompt:'Choose “I am well.”',answer:'元気です',options:['こんにちは','元気です','ありがとう','お元気ですか？']}]},
es:{id:'es-greetings-01',language:'Spanish',code:'es',title:'Your First Spanish Conversation',subtitle:'Say hello, ask how someone is, and respond naturally.',duration:'12 min',xp:50,vocabulary:[['Hola','Hola','Hello'],['¿Cómo estás?','¿Cómo estás?','How are you?'],['Estoy bien','Estoy bien','I am fine'],['Gracias','Gracias','Thank you']],dialogue:[['Anu','¡Hola!','Hello!'],['Ravi','¡Hola! ¿Cómo estás?','Hello! How are you?'],['Anu','Estoy bien. Gracias.','I am fine. Thank you.']],exercises:[{type:'listen',prompt:'What does Gracias mean?',answer:'Thank you',options:['Hello','Thank you','Goodbye','How are you?']},{type:'match',prompt:'What does Hola mean?',answer:'Hello',options:['Hello','Thank you','I am fine','Goodbye']},{type:'order',prompt:'Choose “I am fine.”',answer:'Estoy bien',options:['Hola','Gracias','Estoy bien','¿Cómo estás?']}]},
de:{id:'de-greetings-01',language:'German',code:'de',title:'Your First German Conversation',subtitle:'Build a polite everyday greeting exchange.',duration:'12 min',xp:50,vocabulary:[['Hallo','Hallo','Hello'],['Wie geht es Ihnen?','Wie geht es Ihnen?','How are you?'],['Mir geht es gut','Mir geht es gut','I am fine'],['Danke','Danke','Thank you']],dialogue:[['Anu','Hallo!','Hello!'],['Ravi','Hallo! Wie geht es Ihnen?','Hello! How are you?'],['Anu','Mir geht es gut. Danke.','I am fine. Thank you.']],exercises:[{type:'listen',prompt:'What does Danke mean?',answer:'Thank you',options:['Hello','Thank you','Goodbye','How are you?']},{type:'match',prompt:'What does Hallo mean?',answer:'Hello',options:['Hello','Thank you','I am fine','Sorry']},{type:'order',prompt:'Choose “I am fine.”',answer:'Mir geht es gut',options:['Hallo','Danke','Mir geht es gut','Wie geht es Ihnen?']}]},
ta:{id:'ta-greetings-01',language:'Tamil',code:'ta',title:'Your First Tamil Conversation',subtitle:'Learn a friendly Tamil greeting exchange.',duration:'12 min',xp:50,vocabulary:[['வணக்கம்','Vaṇakkam','Hello'],['எப்படி இருக்கிறீர்கள்?','Eppaṭi irukkiṟīrkaḷ?','How are you?'],['நான் நன்றாக இருக்கிறேன்','Nāṉ naṉṟāka irukkiṟēṉ','I am fine'],['நன்றி','Naṉṟi','Thank you']],dialogue:[['Anu','வணக்கம்!','Hello!'],['Ravi','வணக்கம்! எப்படி இருக்கிறீர்கள்?','Hello! How are you?'],['Anu','நான் நன்றாக இருக்கிறேன். நன்றி.','I am fine. Thank you.']],exercises:[{type:'listen',prompt:'What does நன்றி mean?',answer:'Thank you',options:['Hello','Thank you','Goodbye','How are you?']},{type:'match',prompt:'What does வணக்கம் mean?',answer:'Hello',options:['Hello','Thank you','I am fine','Sorry']},{type:'order',prompt:'Choose “I am fine.”',answer:'நான் நன்றாக இருக்கிறேன்',options:['வணக்கம்','நன்றி','நான் நன்றாக இருக்கிறேன்','எப்படி இருக்கிறீர்கள்?']}]},
te:{id:'te-greetings-01',language:'Telugu',code:'te',title:'Your First Telugu Conversation',subtitle:'Greet someone and respond with confidence.',duration:'12 min',xp:50,vocabulary:[['నమస్కారం','Namaskāram','Hello'],['మీరు ఎలా ఉన్నారు?','Mīru elā unnāru?','How are you?'],['నేను బాగున్నాను','Nēnu bāgunnānu','I am fine'],['ధన్యవాదాలు','Dhanyavādālu','Thank you']],dialogue:[['Anu','నమస్కారం!','Hello!'],['Ravi','నమస్కారం! మీరు ఎలా ఉన్నారు?','Hello! How are you?'],['Anu','నేను బాగున్నాను. ధన్యవాదాలు.','I am fine. Thank you.']],exercises:[{type:'listen',prompt:'What does ధన్యవాదాలు mean?',answer:'Thank you',options:['Hello','Thank you','Goodbye','How are you?']},{type:'match',prompt:'What does నమస్కారం mean?',answer:'Hello',options:['Hello','Thank you','I am fine','Sorry']},{type:'order',prompt:'Choose “I am fine.”',answer:'నేను బాగున్నాను',options:['నమస్కారం','ధన్యవాదాలు','నేను బాగున్నాను','మీరు ఎలా ఉన్నారు?']}]}
};

export const lesson = seedLessons.kn;
export const lessons = seedLessons;
export function getLesson(code:string): Lesson { return seedLessons[code] ?? seedLessons.kn; }
export function getLanguage(code:string): Language { return languages.find(l=>l.code===code) ?? languages[0]; }
export const levels=[['Discovery','Sounds, scripts & first words','done'],['Beginner','Useful words & simple sentences','current'],['Elementary','Daily conversations','locked'],['Intermediate','Stories & flexible grammar','locked'],['Upper Intermediate','Natural conversation','locked'],['Advanced','Nuance & expression','locked'],['Professional','Work, study & specialist language','locked'],['Mastery','Near-fluent communication','locked']];
export const skills=[['Speaking',84],['Listening',91],['Reading',76],['Writing',68],['Grammar',81],['Vocabulary',88]];
